schema:
  - backend/schema/*.graphql
exec:
  filename: backend/generated/generated.go
  package: generated
model:
  filename: backend/generated/models_generated.go
  package: generated
resolver:
  layout: follow-schema
  dir: backend/resolver
  package: resolver
