schema:
  - ./backend/schema/*.graphql
exec:
  filename: backend/generated/exec_generated.go
  package: generated
model:
  filename: backend/generated/model_generated.go
  package: generated
resolver:
  layout: follow-schema
  dir: backend/resolvers
  package: resolvers
