#!/bin/bash

function dgraph_cleanup()
{
	echo && echo "::: starting cleanup :::"
	killall dgraph > /dev/null
	exit
}

trap dgraph_cleanup SIGINT

echo "::: running dgraph zero :::"
dgraph zero --my=localhost:5080 &
sleep 10

echo "::: running dgraph alpha :::"
dgraph alpha --lru_mb=2048 --my=localhost:7080 --zero=localhost:5080 &
sleep 10

echo "::: uploading dgraph schema :::"
curl -X POST localhost:8080/admin/schema --data-binary '@database/schema.graphql' > /dev/null

echo "::: dgraph running and serving schema :::"

while true
do
	sleep 10
done
